In [1]:
from sklearn import tree
import pandas as pd
import os

In [3]:
df = pd.read_csv(os.path.join("data", "final_dataset.csv"))
df.head()

,Year,Player,Pos,Age,Team,Championship Wins,RunnerUp Count,TRB,AST,STL,BLK,TOV,PF,PER,FG%,3P%,FTA,FT%,PTS
0,1951,Paul Arizin,SF,22,Philadelphia Warriors,0.0,0.0,640.0,138,0.0,0.0,0.0,284,0.0,0.407,0.0,526,0.793,1121
1,1952,Paul Arizin,SF,23,Philadelphia Warriors,0.0,0.0,745.0,170,0.0,0.0,0.0,250,25.5,0.448,0.0,707,0.818,1674
2,1955,Paul Arizin,SF,26,Philadelphia Warriors,0.0,0.0,675.0,210,0.0,0.0,0.0,270,18.2,0.399,0.0,585,0.776,1512
3,1956,Paul Arizin,SF,27,Philadelphia Warriors,0.0,0.0,539.0,189,0.0,0.0,0.0,282,21.3,0.448,0.0,626,0.810,1741
4,1957,Paul Arizin,SF,28,Philadelphia Warriors,0.0,0.0,561.0,150,0.0,0.0,0.0,274,22.2,0.422,0.0,713,0.829,1817

In [ ]:
target = df["Championship Wins"]
target_names = ["negative", "positive"]