In [4]:
from sklearn import tree
import pandas as pd
import os

In [5]:
df = pd.read_csv(os.path.join("data", "final_dataset.csv"))
df.head()

,Year,Player,Pos,Age,Team,Championship Wins,RunnerUp Count,TRB,AST,STL,BLK,TOV,PF,PER,FG%,3P%,FTA,FT%,PTS,Championship Appearance Y/N
0,1951,Paul Arizin,SF,22,Philadelphia Warriors,0.0,0.0,640.0,138,0.0,0.0,0.0,284,0.0,0.407,0.0,526,0.793,1121,0
1,1952,Paul Arizin,SF,23,Philadelphia Warriors,0.0,0.0,745.0,170,0.0,0.0,0.0,250,25.5,0.448,0.0,707,0.818,1674,0
2,1955,Paul Arizin,SF,26,Philadelphia Warriors,0.0,0.0,675.0,210,0.0,0.0,0.0,270,18.2,0.399,0.0,585,0.776,1512,0
3,1956,Paul Arizin,SF,27,Philadelphia Warriors,0.0,0.0,539.0,189,0.0,0.0,0.0,282,21.3,0.448,0.0,626,0.810,1741,0
4,1957,Paul Arizin,SF,28,Philadelphia Warriors,0.0,0.0,561.0,150,0.0,0.0,0.0,274,22.2,0.422,0.0,713,0.829,1817,0

In [6]:
target = df["Championship Appearance Y/N"]
target_names = ["negative", "positive"]

In [19]:
data = df.drop(["Championship Appearance Y/N", "Player", "Team", "Pos", "Year", "Championship Wins", "RunnerUp Count"], axis=1)
feature_names = data.columns
data.head()

   Age    TRB  AST  STL  BLK  TOV   PF   PER    FG%  3P%  FTA    FT%   PTS
0   22  640.0  138  0.0  0.0  0.0  284   0.0  0.407  0.0  526  0.793  1121
1   23  745.0  170  0.0  0.0  0.0  250  25.5  0.448  0.0  707  0.818  1674
2   26  675.0  210  0.0  0.0  0.0  270  18.2  0.399  0.0  585  0.776  1512
3   27  539.0  189  0.0  0.0  0.0  282  21.3  0.448  0.0  626  0.810  1741
4   28  561.0  150  0.0  0.0  0.0  274  22.2  0.422  0.0  713  0.829  1817

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [34]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=400)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.6637835848362165

In [35]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.08940628855986439, 'TRB'),
 (0.08872819362948128, 'PER'),
 (0.0875009991140852, 'AST'),
 (0.08743705092154391, 'PTS'),
 (0.08493765428549216, 'Age'),
 (0.08467945546481737, 'PF'),
 (0.0834230965257815, 'FG%'),
 (0.0824220703191412, 'FTA'),
 (0.07887058666556784, 'FT%'),
 (0.064787773689295, 'STL'),
 (0.0640052903515182, 'TOV'),
 (0.05919905125118592, 'BLK'),
 (0.044602489222226066, '3P%')]